/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rileylundquist_liftsense_CameraActivity */

#ifndef _Included_com_rileylundquist_liftsense_CameraActivity
#define _Included_com_rileylundquist_liftsense_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rileylundquist_liftsense_CameraActivity
 * Method:    nativeColorDetect
 * Signature: (J)V
 */
JNIEXPORT jfloat JNICALL Java_com_rileylundquist_liftsense_CameraActivity_nativeColorDetect
  (JNIEnv *, jobject, jlong);

/*JNIEXPORT jfloat JNICALL Java_com_rileylundquist_liftsense_CameraActivity_nativeColorDetect2
(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint);*/

#ifdef __cplusplus
}
#endif
#endif
