/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_rileylundquist_liftsense_MainActivity.h"
/*
 * Class:     com_rileylundquist_liftsense_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rileylundquist_liftsense_MainActivity_stringFromJNI
  (JNIEnv * env, jobject obj) {
    return (*env)->NewStringUTF(env, "Hello from JNI");
  }